### PR TITLE
merge dev to master in PFD

### PR DESCRIPTION
**Pull request by ProFireDev**

### CODE REVIEW

**Comment by vtheskeleton** [comment]
IT SEEMS YOU HAVE EDITED CONFIF

**Comment by vtheskeleton** [comment]
Hgsjskdfkqvdh7dbf

**Comment by ProFireDev** [comment]
> IT SEEMS YOU HAVE EDITED CONFIF
yea I had to removed my user ID and replace it back with yours and  vuks, it seems to be working okay so I'm gonna merge it

**Comment by ProFireDev** [comment]
approved

**Pull request merged**
